<?php
use App\Http\Controllers\{AuthController,AttendanceController,PortalController};use Illuminate\Support\Facades\Route;
Route::middleware('guest')->group(function(){Route::get('/login',[AuthController::class,'show'])->name('login');Route::post('/login',[AuthController::class,'login'])->name('login.store');});
Route::post('/logout',[AuthController::class,'logout'])->middleware('auth')->name('logout');
Route::middleware(['auth','role:teacher'])->prefix('teacher')->name('teacher.')->group(function(){Route::get('/dashboard',[PortalController::class,'teacher'])->name('dashboard');Route::get('/classes/{class}/attendance',[AttendanceController::class,'show'])->name('attendance.show');Route::put('/classes/{class}/attendance',[AttendanceController::class,'save'])->name('attendance.save');Route::post('/attendance/{session}/submit',[AttendanceController::class,'submit'])->name('attendance.submit');Route::get('/classes/{class}/students',[PortalController::class,'students'])->name('students');Route::get('/students/{student}',[PortalController::class,'student'])->name('student');Route::get('/classes/{class}/timetables',[PortalController::class,'timetables'])->name('timetables');Route::post('/classes/{class}/timetables',[PortalController::class,'saveTimetable'])->name('timetables.save');});
Route::middleware(['auth','role:administrator'])->prefix('admin')->name('administrator.')->group(function(){Route::get('/dashboard',[PortalController::class,'admin'])->name('dashboard');Route::get('/classes/{class}',[PortalController::class,'adminClass'])->name('class');Route::get('/students/{student}',[PortalController::class,'student'])->name('student');Route::get('/teachers',[PortalController::class,'teachers'])->name('teachers');Route::post('/teachers',[PortalController::class,'createTeacher'])->name('teachers.create');});
Route::middleware(['auth','role:ceo'])->prefix('ceo')->name('ceo.')->group(function(){Route::get('/dashboard',[PortalController::class,'ceo'])->name('dashboard');Route::get('/schools/{school}',[PortalController::class,'school'])->name('school');Route::get('/classes/{class}',[PortalController::class,'ceoClass'])->name('class');Route::get('/students/{student}',[PortalController::class,'student'])->name('student');});
Route::middleware('auth')->group(function(){Route::get('/reports',[PortalController::class,'report'])->name('reports');Route::get('/reports/export',[PortalController::class,'csv'])->name('reports.csv');});
Route::redirect('/','/login');
