<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration {
    public function up(): void {
        Schema::create('schools', function (Blueprint $t) {$t->id();$t->string('name');$t->string('code')->unique();$t->text('address')->nullable();$t->string('district')->nullable();$t->string('status')->default('active');$t->timestamps();});
        Schema::create('users', function (Blueprint $t) {$t->id();$t->foreignId('school_id')->nullable()->constrained()->nullOnDelete();$t->string('name');$t->string('email')->unique();$t->string('role');$t->timestamp('email_verified_at')->nullable();$t->string('password');$t->rememberToken();$t->timestamps();$t->index(['school_id','role']);});
        Schema::create('profiles', function (Blueprint $t) {$t->id();$t->foreignId('user_id')->unique()->constrained()->cascadeOnDelete();$t->string('phone')->nullable();$t->string('address')->nullable();$t->timestamps();});
        Schema::create('teachers', function (Blueprint $t) {$t->id();$t->foreignId('user_id')->unique()->constrained()->cascadeOnDelete();$t->foreignId('school_id')->constrained()->restrictOnDelete();$t->string('employee_id');$t->string('full_name');$t->string('phone')->nullable();$t->string('status')->default('active');$t->timestamps();$t->unique(['school_id','employee_id']);});
        Schema::create('classes', function (Blueprint $t) {$t->id();$t->foreignId('school_id')->constrained()->restrictOnDelete();$t->string('name');$t->unsignedTinyInteger('grade');$t->string('section');$t->string('academic_year');$t->string('status')->default('active');$t->timestamps();$t->unique(['school_id','grade','section','academic_year']);$t->index('school_id');});
        Schema::create('teacher_class_assignments', function (Blueprint $t) {$t->id();$t->foreignId('teacher_id')->constrained()->cascadeOnDelete();$t->foreignId('class_id')->constrained('classes')->restrictOnDelete();$t->date('start_date');$t->date('end_date')->nullable();$t->boolean('is_current')->default(true);$t->timestamps();$t->index(['teacher_id','is_current']);$t->index(['class_id','is_current']);});
        Schema::create('students', function (Blueprint $t) {$t->id();$t->foreignId('school_id')->constrained()->restrictOnDelete();$t->foreignId('class_id')->constrained('classes')->restrictOnDelete();$t->string('student_id');$t->string('full_name');$t->string('parent_name')->nullable();$t->string('parent_phone')->nullable();$t->string('status')->default('active');$t->timestamps();$t->unique(['school_id','student_id']);$t->index('class_id');});
        Schema::create('attendance_sessions', function (Blueprint $t) {$t->id();$t->foreignId('school_id')->constrained()->restrictOnDelete();$t->foreignId('class_id')->constrained('classes')->restrictOnDelete();$t->foreignId('teacher_id')->nullable()->constrained()->nullOnDelete();$t->date('attendance_date');$t->string('status')->default('in_progress');$t->timestamp('submitted_at')->nullable();$t->timestamp('locked_at')->nullable();$t->timestamps();$t->unique(['class_id','attendance_date']);$t->index(['school_id','attendance_date']);});
        Schema::create('attendance_records', function (Blueprint $t) {$t->id();$t->foreignId('attendance_session_id')->constrained()->cascadeOnDelete();$t->foreignId('student_id')->constrained()->restrictOnDelete();$t->enum('status',['present','absent','late']);$t->timestamps();$t->unique(['attendance_session_id','student_id']);$t->index('student_id');});
        Schema::create('class_timetables', function (Blueprint $t) {$t->id();$t->foreignId('class_id')->constrained('classes')->cascadeOnDelete();$t->unsignedTinyInteger('day_of_week');$t->time('start_time');$t->time('end_time');$t->string('subject');$t->string('room')->nullable();$t->foreignId('teacher_id')->nullable()->constrained()->nullOnDelete();$t->timestamps();$t->unique(['class_id','day_of_week','start_time']);});
        Schema::create('teacher_timetables', function (Blueprint $t) {$t->id();$t->foreignId('teacher_id')->constrained()->cascadeOnDelete();$t->foreignId('class_id')->constrained('classes')->cascadeOnDelete();$t->unsignedTinyInteger('day_of_week');$t->time('start_time');$t->time('end_time');$t->string('subject');$t->string('room')->nullable();$t->timestamps();$t->unique(['teacher_id','day_of_week','start_time']);});
        Schema::create('announcements', function (Blueprint $t) {$t->id();$t->foreignId('school_id')->nullable()->constrained()->nullOnDelete();$t->foreignId('created_by')->constrained('users')->restrictOnDelete();$t->string('title');$t->text('message');$t->enum('audience',['organization','school','teacher']);$t->timestamps();});
        Schema::create('sms_notifications', function (Blueprint $t) {$t->id();$t->foreignId('student_id')->constrained()->restrictOnDelete();$t->foreignId('attendance_session_id')->nullable()->constrained()->nullOnDelete();$t->string('parent_phone');$t->text('message');$t->enum('status',['queued','simulated','sent','failed'])->default('queued');$t->timestamp('queued_at')->nullable();$t->timestamp('sent_at')->nullable();$t->string('provider_reference')->nullable();$t->timestamps();});
        Schema::create('audit_logs', function (Blueprint $t) {$t->id();$t->foreignId('user_id')->nullable()->constrained()->nullOnDelete();$t->string('action');$t->string('entity');$t->unsignedBigInteger('entity_id')->nullable();$t->json('metadata')->nullable();$t->timestamp('created_at')->useCurrent();$t->index(['entity','entity_id']);});
        Schema::create('notification_preferences', function (Blueprint $t) {$t->id();$t->foreignId('user_id')->unique()->constrained()->cascadeOnDelete();$t->boolean('browser_reminders')->default(true);$t->boolean('sound_enabled')->default(false);$t->timestamps();});
        Schema::create('password_reset_tokens', function (Blueprint $t) {$t->string('email')->primary();$t->string('token');$t->timestamp('created_at')->nullable();});
        Schema::create('sessions', function (Blueprint $t) {$t->string('id')->primary();$t->foreignId('user_id')->nullable()->index();$t->string('ip_address',45)->nullable();$t->text('user_agent')->nullable();$t->longText('payload');$t->integer('last_activity')->index();});
    }
    public function down(): void { Schema::dropIfExists('sessions');Schema::dropIfExists('password_reset_tokens');Schema::dropIfExists('notification_preferences');Schema::dropIfExists('audit_logs');Schema::dropIfExists('sms_notifications');Schema::dropIfExists('announcements');Schema::dropIfExists('teacher_timetables');Schema::dropIfExists('class_timetables');Schema::dropIfExists('attendance_records');Schema::dropIfExists('attendance_sessions');Schema::dropIfExists('students');Schema::dropIfExists('teacher_class_assignments');Schema::dropIfExists('classes');Schema::dropIfExists('teachers');Schema::dropIfExists('profiles');Schema::dropIfExists('users');Schema::dropIfExists('schools'); }
};
